[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "zbinfigs"
version = "0.0.0"
authors = [
  { name="Isaac Spackman", email="ispackman@mines.edu" },
]
description = "A package for figure classification from a zotero collection of scholarly articles"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

