[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "zbinfigs"
version = "0.0.0"
authors = [
  { name="Isaac Spackman", email="ispackman@mines.edu" },
]
description = "A package for figure classification from a zotero collection of scholarly articles"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
test = [
    "pytest",
    "coverage"
]
docs = [
  "furo",
  "myst_parser >=0.13",
  "sphinx >=4.0",
  "sphinx-copybutton",
  "sphinx-autodoc-typehints",
]

[project.urls]
"Source Code" = "https://github.com/spackman/zbinfigs"


[tool.hatch.build.targets.wheel]
packages = ["src"]

# Ruff Linter
[tool.ruff]
src = ["src"]
extend-include = ["*.ipynb"]

# Use Numpy-style docstrings.
[tool.ruff.lint]
select = ["D"]
[tool.ruff.lint.pydocstyle]
convention = "numpy"